apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiulogin
  namespace: fiu
  labels:
    app: fiulogin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiulogin
  template:
    metadata:
      labels:
        app: fiulogin
    spec:
      containers:
      - name: fiulogin
        image: r0bdocker/testlogin3:v4
        ports:
        - containerPort: 80

